### ISSUE TITLE
Original message being sent to worker

### ISSUE THREAD

**Issue by christkv** [cramforce/node-worker#1]
Using the example in an express application and calling posting a message to a worker will return 2 messages from the worker.
1. The original message sent to the worker
2. The message from the worker

Is this the expected behavior ?

**Comment by cramforce** [comment]
Hey,

is this master or the unixsockets branch?

**Comment by cramforce** [comment]
Please go back to 90b6f7ee9deb0b866eb386df2463d811936c50e8 and try that or use the branch.
